### ISSUE TITLE
BROKEN v1.1.0 !!!

### ISSUE THREAD

**Issue by keradus** [Esri/terraformer-wkt-parser#14]
Cannot install v1.1.0

Reason: https://github.com/Esri/terraformer-wkt-parser/commit/389487f59218dcc101c9a574e8ea26943a9e2225#diff-0a08a7565aba4405282251491979bb6bR7
ref https://github.com/Esri/terraformer-wkt-parser/issues/8

terraformer 1.0.5 is not yet released!

```
bower install terraformer-wkt-parser

bower not-cached    git://github.com/Esri/Terraformer.git#~1.0.5
bower resolve       git://github.com/Esri/Terraformer.git#~1.0.5
bower ENORESTARGET  No tag found that was able to satisfy ~1.0.5

Additional error details:
Available versions in git://github.com/Esri/Terraformer.git: 1.0.4, 1.0.3, 1.0.2, 1.0.1
```

**Comment by jgravois** [comment]
i just tagged the necessary `terraformer` [release](https://github.com/Esri/Terraformer/releases/tag/v1.0.5) on github.  `v1.0.5` published a year ago on [npm](https://www.npmjs.com/package/terraformer), but a github tag is needed for bower.

installation is working for me now, but i'll wait for you to confirm before closing this issue.
```
bower install terraformer-wkt-parser
```

**Comment by keradus** [comment]
Thank you!
I just check this out and now it's working.
