### ISSUE TITLE
support for converting FeatureCollection to WKT

### ISSUE THREAD

**Issue by jameslaneconkling** [Esri/terraformer-wkt-parser#16]
Converting geoJSON FeatureCollection to WKT throws an error:

```
Uncaught Error: Unknown Type: FeatureCollection(…)
```

Are FeatureCollections not supported?

Thanks for the help.

**Comment by jgravois** [comment]
the library provides support converting back and forth between GeoJSON [geometry objects](http://geojson.org/geojson-spec.html#geometry-objects) and WKT geometries.  as such, either a `Point`, `LineString`, `Polygon` `MultiPoint`, `MultiLineString` or `MultiPolygon` is what the `convert()` is expecting you to pass it.

this means it's up to you to loop through the features in your own FeatureCollection to extract the geometries of interest and convert them.

[relevant source](https://github.com/Esri/terraformer-wkt-parser/blob/master/src/module-source.js#L295-L305)

if you need additional assistance, i'm happy to chat further.  at the very least, we should include a little more info in the documentation to clarify the point.

**Comment by jameslaneconkling** [comment]
ah, OK, makes sense.  will just go ahead and parse myself (hadn't realized how simple WKT `GEOMETRYCOLLECTION(...)` was.

Thanks for the clarification.
