### ISSUE TITLE
Error: Cannot find module with sequelize in 1.1.1 

### ISSUE THREAD

**Issue by mchelen** [Esri/terraformer-wkt-parser#23]
When running `./node_modules/.bin/sequelize db:migrate` I get `Error: Cannot find module 'terraformer-wkt-parser'`

If I force terraformer-wkt-parser to version `1.1.0` there is no error.

**Comment by pezza3434** [comment]
Yup, this has broke sequelize

**Comment by jgravois** [comment]
thanks guys.  i'm checking into this now.

**Comment by pezza3434** [comment]
@jgravois - Thanks a lot. Really appreciated.

**Comment by jgravois** [comment]
i see the problem. in the latest release the built files are nested inside a `dist/` directory.
```
dist/
  terraformer-wkt-parser.js
  terraformer-wkt-parser.min.js
```

i'll publish `1.1.2` (with the appropriate original structure) here in a few minutes.

**Comment by jgravois** [comment]
okay.  [`1.1.2`](https://www.npmjs.com/package/terraformer-wkt-parser) is now published.  if someone can confirm whether or not the problem is resolved, i'd appreciate it.

**Comment by santiag00** [comment]
everything's back to normal, thanks!

**Comment by jgravois** [comment]
no problem. sincerely sorry for the inconvenience.

**Comment by pezza3434** [comment]
@jgravois No worries at all. Huge thumbs up for how quick you responded.
