### ISSUE TITLE
Geometry Collection support not released

### ISSUE THREAD

**Issue by gianalvarezblanes** [Esri/terraformer-wkt-parser#32]
Support for GeometryCollection was committed and appears to be ready, but a release was never made. 1.1.2 does not include these changes.

**Comment by jgravois** [comment]
my instinct is to:

- [ ] ensure that the GeoJSON ring-winding order output by this library is [RFC 7946](https://tools.ietf.org/html/rfc7946) compliant (see https://github.com/Esri/arcgis-to-geojson-utils/issues/21, #15 )
- [ ] write a script to automate publishing each release (see #22)
- [ ] release `v.1.2.0`

this will obviously take longer than just tagging what is in the repo now manually, but it will get us to inbox zero _and_ make it easier to start publishing new features/bug fixes immediately in the future as they trickle in.

**Comment by jgravois** [comment]
[`v1.2.0`](https://github.com/Esri/terraformer-wkt-parser/releases/tag/v1.2.0) can now be found on both GitHub and npm. enjoy!

**Comment by gianalvarezblanes** [comment]
Great! Thank you so much!
