### ISSUE TITLE
terraformer-wkt-parser.d.ts references to GeoJSON

### ISSUE THREAD

**Issue by WORMSS** [Esri/terraformer-wkt-parser#38]
I had to add `import GeoJson from 'geojson';` to 
```
import GeoJson from 'geojson';
export = WKT;
declare namespace WKT {
    export function parse(wkt: string): GeoJSON.GeometryObject;
    export function convert(geoJSON: GeoJSON.GeometryObject): string;
}
```
To make this work in VSCode
Though, also had to do `npm i @types/geojson` also.

**Comment by jgravois** [comment]
> I had to add import GeoJson from 'geojson';

Another option would be to declare the external dependency the way we do [here](https://github.com/Esri/terraformer-arcgis-parser/blob/c7af3110f8219db6605a111844f0febb46cf8e9e/index.d.ts#L1). Either way, a PR with an improvement would be welcome.

```ts
/// <reference types="geojson" />
```

> also had to do npm i @types/geojson

Not sure what else we can do to help with that. `@types/geojson` is already listed as a dependency of this lib.

https://github.com/Esri/terraformer-wkt-parser/blob/dd2885db4614dbf4189973709b9f94123e11ad26/package.json#L14

**Comment by WORMSS** [comment]
Yeah, I actually went a little farther with changing some other files to get exactly what I needed. I am not 100% with everything I did to get things to work. I need to undo things but the app is currently running for the next few hours. I will make a proper report in the morning (BST) with everything I did.

**Comment by DarkFIxED** [comment]
So, is there some progress? I really need this fix.

**Comment by DarkFIxED** [comment]
Thank you very much!

**Comment by joseph-galindo** [comment]
#40 seems to have broken use cases where an external dependency exists for @types/geojson on a version other than 1.x. For example, cases like:

sample package.json
```
"dependencies": {
   ...,
   "terraformer-wkt-parser": "1.2.1",
   ...
},
"devDependencies": {
   ...,
   "@types/geojson": "7946.0.7",
   ...
}
```

sample TypeScript source code
```
import terraWkt from 'terraformer-wkt-parser';
import * as GeoJSON from 'geojson';

const sampleWkt = '...';
const parsedWkt: GeoJSON.GeometryObject = terraWkt.parse(sampleWkt);
      ^^^^^^^^^
Type 'GeometryObject' is not assignable to type 'Geometry'.
  Type 'DirectGeometryObject' is not assignable to type 'Geometry'.
    Type 'DirectGeometryObject' is not assignable to type 'MultiPolygon'.
      Types of property 'type' are incompatible.
        Type 'string' is not assignable to type '"MultiPolygon"'.ts(2322)
```

The same sample block above works with `terraformer-wkt-parser@1.2.0`.

**Comment by jgravois** [comment]
Thanks for the repot. I'm no typescript expert, but it looks like you can fix the problem and regain control over the version of the typings you'd like to be using in your own application by making sure to import them _before_ you import from terraformer.

```ts
import * as GeoJSON from 'geojson'
import terraWkt from 'terraformer-wkt-parser';

const parsedWkt: GeoJSON.GeometryObject = terraWkt.parse(sampleWkt);
```

**Comment by joseph-galindo** [comment]
@jgravois I wasn't expecting this to work at first, but it strangely does seem to work. I'm guessing moving the import up somehow "shadows" over the `GeoJSON` that the types for terraformer-wkt-parser try to reference, since GeoJSON itself is exported as a global namespace?

Specifically this part: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/geojson/index.d.ts#L14

**Comment by jgravois** [comment]
> the import order is actually influencing the type definitions that terraformer-wkt-parser is trying to use internally?

tbh, I'm not sure.

your import might be overriding the definitions our parser declares as a dependency internally or maybe it's just a lucky coincidence that they are compatible.
