### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by DarkFIxED** [Esri/terraformer-wkt-parser#45]
Please update npm package (https://www.npmjs.com/package/terraformer-wkt-parser) in order of latest changes

**Comment by jgravois** [comment]
[`v1.2.1`](https://github.com/Esri/terraformer-wkt-parser/releases/tag/v1.2.1) has been released.

I added a [`CONTRIBUTING.md`](https://github.com/Esri/terraformer-wkt-parser/blob/807579b89d3bc6326f959ee37dcc07ac045b253c/CONTRIBUTING.md#release-instructions-for-maintainers) file with instructions for maintainers to publish a release. @gavinr you think you can tackle the next one?
