### ISSUE TITLE
unable to parse scientific notation numbers (i.e 1.234E-4)

### ISSUE THREAD

**Issue by tfordon** [Esri/terraformer-wkt-parser#7]
I cannot parse WKTs that use scientific notation, so something like: 'POINT (3.234E-2 10)' doesn't work, even though this seems proper.  I didn't have access to the ISO, but it is allowed in the OpenGIS implementation specification.

Here is a jsfiddle that demonstrates my problem:
http://jsfiddle.net/qfxxLx95/4/

**Comment by ojsdude** [comment]
Hi Tom,
I am having a similar issue at the moment. I know it was a while ago, but I wondered if you ever found a solution to the problem?

Thanks,

Oliver

**Comment by tfordon** [comment]
We ended up working around the issue by having the tool that generated the WKT not produce scientific notation.

**Comment by tfordon** [comment]
I looked a little closer.  I think it should be a pretty small change.  I can't try it now, but maybe tonight.

This file defines the grammar:  terraformer-wkt-parser/src/wkt.yy

I think we can just change line 10 to be:
"-"?[0-9]+("."[0-9]+)?([eE][\-\+]?[0-9]+)? return 'DOUBLE_TOK'

The DOUBLE_TOK tokens seem to be passed into Number which supports sci-notation.

I'll try it soon, but feel free to try it and submit the pull request if you don't want to wait on me Oliver.

**Comment by jgravois** [comment]
closed by your own f11b0e6e8df1a885b6fab0b28d9838cd01b45fe4.  thank you!
