### ISSUE TITLE
Update to latest terraformer

### ISSUE THREAD

**Issue by tcoopman** [Esri/terraformer-wkt-parser#8]
Terraformer is at 1.0.4, you include 0.1.7

**Comment by keradus** [comment]
:+1:

any news on that?

**Comment by jgravois** [comment]
resolved by 389487f59218dcc101c9a574e8ea26943a9e2225.  thanks for reporting.

version `1.1.0` has been tagged and published on github, [npm](https://www.npmjs.com/package/terraformer-wkt-parser) and our [CDN](http://cdn-geoweb.s3.amazonaws.com/terraformer-wkt-parser/1.1.0/terraformer-wkt-parser.min.js).
