### ISSUE TITLE
Informative parse errors

### ISSUE THREAD

**Issue by sckott** [Esri/terraformer-wkt-parser#9]
Currently on error `parse` gives e..g, 

```js
var wkt = require('terraformer-wkt-parser');
wkt.parse('LINESTRING (30 10, 10 30, 40 a)')
```

```js
Error: Unable to parse
```

Any chance more informative error messages can be passed?

**Comment by JerrySievert** [comment]
we might be able to pass back the portion of the line that the parser fails on, i can look into that.

we're using `JISON` under the hood with a `BNF` grammar to generate the actual parser.

**Comment by sckott** [comment]
thanks for considering this :)

**Comment by JerrySievert** [comment]
looks like it *should* be working, but i'll try to find some time tomorrow to investigate why it isn't:

https://github.com/Esri/terraformer-wkt-parser/blob/master/src/module-source.js#L111

**Comment by JerrySievert** [comment]
looks like the error wasn't being properly thrown and the second argument never got printed.

this is what it *should* look like:

```
Error: Unable to parse: Error: Parse error on line 1:
...G (30 10, 10 30, 40 a)
-----------------------^
Expecting 'DOUBLE_TOK', got 'INVALID'
```

updating to make that happen.

**Comment by sckott** [comment]
great! that looks quite useful

**Comment by JerrySievert** [comment]
it is, and indeed it is as useful as it was meant to be :)

just finishing up getting it all built and packaged and should hopefully have a release out shortly.  i'll close the ticket when that happens.

**Comment by sckott** [comment]
:+1:

**Comment by JerrySievert** [comment]
done and live
